### ISSUE TITLE
Cant be able to fetch the only fields of products.

### ISSUE THREAD

**Issue by Noushad-web** [swellstores/swell-js#55]
Hi there, If I want to only fetch the required fields then there is no documentation of how we can implement this on swell-js documentation.
`https://{{swell-id}}:{{publicKey}}@api.swell.store/products?fields=slug`

**I'm using this custom way to get the only fields**
but This npm package is not providing any way to fetch the selected fields

**Comment by logeshswell** [comment]
@Noushad-web 
Frontend API (or `swell-js`) would return all the corresponding response fields and it doesn't support for fetching the required fields like Backend API (or `swell-node`) does.

And, you can fetch the required fields via Backend API (or `swell-node`) as you mentioned as follows, except that backend `secret-key` should be passed instead of `public-key`
> https://{{swell-id}}:{{~~public-key~~ secret-key}}@api.swell.store/products?fields=slug
